version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/your_domain.com/your_domain.com.crt:/etc/v2ray/certificate.crt
      - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/your_domain.com/your_domain.com.key:/etc/v2ray/private.key
    ports:
      - "10086:10086"
    command: ["run", "-c", "/etc/v2ray/config.json"]
